version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: tracing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracing_db
    ports:
      - "5449:5432"

volumes:
  postgres_data:
